SSAFIT/BE

.project, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/PostDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Post.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/resources/mapper/postMapper.xml
=> [POST] 영상 게시글 생성 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/ExceptionControllerAdvice.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java
=> [POST] 영상 게시글 조회 기능 구현 

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/resources/mapper/postMapper.xml
=> [POST] 영상 게시글 수정 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java
=> [POST] 영상 게시글 삭제 기능 구현 

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/exception/IdIncorrectException.java, Ssafit/src/main/java/com/ssafy/ssafit/exception/PwIncorrectException.java, Ssafit/src/main/java/com/ssafy/ssafit/exception/UserNotFoundException.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/UserDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/userMapper.xml
=> [USER] 유저 조회 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/CommentController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/CommentDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/ReplyDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Comment.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Reply.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentServiceImpl.java, Ssafit/src/main/resources/mapper/commentMapper.xml
=> [COMMENT] 댓글 CRUD 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java
=> [USER] 유저 수정 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/UserDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/userMapper.xml
=> [USER] 유저 삭제 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/CommentController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/CommentDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentServiceImpl.java, Ssafit/src/main/resources/mapper/commentMapper.xml
=> [COMMENT] 댓글 조회 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/RelationshipController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/RelationshipDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/RelationshipService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/RelationshipServiceImpl.java, Ssafit/src/main/resources/mapper/relationshipMapper.xml
=> [RELATIONSHIP] 관계 CD 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/UserDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/userMapper.xml
=> [USER] 유저 팔로워/팔로잉 목록 조회 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/CommentController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/ReplyController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/CommentDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/ReplyDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/CommentResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyServiceImpl.java, Ssafit/src/main/resources/mapper/commentMapper.xml, Ssafit/src/main/resources/mapper/replyMapper.xml
=> [REPLY] 대댓글 CRUD 기능 구현, 댓글 RU 기능 수정

Ssafit/pom.xml
=> [CONFIG] lombok 추가

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/PostDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/PostResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/resources/mapper/postMapper.xml
=> [POST] 연령, 성별 좋아요 누른 TopRank POST R 기능 구현 

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/CommentController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/ReplyController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/ReplyDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Comment.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/CommentResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/MyComment.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyServiceImpl.java, Ssafit/src/main/resources/mapper/commentMapper.xml, Ssafit/src/main/resources/mapper/replyMapper.xml
#37 댓글 삭제 컬럼 추가 & 마이페이지 댓글목록 조회 기능 구현 완료했습니다!
=> [COMMENT&REPLY] 댓글 삭제 컬럼 추가 & 마이페이지 댓글목록 조회 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/CommentController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/ReplyController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/CommentDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/ReplyDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Comment.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/CommentResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/MyComment.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Reply.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/CommentServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/ReplyServiceImpl.java, Ssafit/src/main/resources/mapper/commentMapper.xml, Ssafit/src/main/resources/mapper/replyMapper.xml
=> [REFACTOR] 댓글 대댓글 코드 리팩토링

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/LikeController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/LikeDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/PostDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Like.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Post.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/PostResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/LikeService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/LikeServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/likeMapper.xml, Ssafit/src/main/resources/mapper/postMapper.xml
=> [REFACTOR] POST&LIKE 코드 정리

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/RelationshipController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/exception/PwIncorrectException.java, Ssafit/src/main/java/com/ssafy/ssafit/exception/UserNotFoundException.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/RelationshipDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/UserDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Image.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Relationship.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/User.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/FileUploadService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/FileUploadServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/RelationshipService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/RelationshipServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/S3Service.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/S3ServiceImpl.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/relationshipMapper.xml, Ssafit/src/main/resources/mapper/userMapper.xml
=> [REFACTOR] USER&FILE&RELATIONSHIP 코드 정리

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java
=> [REFACTOR] USER 코드 수정

Ssafit/src/main/java/com/ssafy/ssafit/model/dto/Post.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dto/PostResponse.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/resources/mapper/postMapper.xml
=> [POST] POST DTO 수정

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/LikeController.java, Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/PostController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/PostDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/PostServiceImpl.java, Ssafit/src/main/resources/mapper/postMapper.xml
=> [POST] 유저가 좋아요 누른 파트별 영상 리스트 조회 기능 구현

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java
#62 
1.  status 리턴 방식 변경
2. 아이디 존재 유무 판별 추가
=> [REFACTOR] 로그인 수정

Ssafit/src/main/java/com/ssafy/ssafit/controller/rest/UserController.java, Ssafit/src/main/java/com/ssafy/ssafit/model/dao/UserDao.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserService.java, Ssafit/src/main/java/com/ssafy/ssafit/model/service/UserServiceImpl.java, Ssafit/src/main/resources/mapper/userMapper.xml
=> [USER] USER 검색 조회 기능 구현
